In [5]:
import numpy as np
import pandas as pd

# Step 1: Load the training and test data
train_data = pd.read_csv("training-part-2.csv")
test_data = pd.read_csv("test-part-2.csv")

# Step 2: Separate the feature vectors and classes
train_features = train_data.iloc[:, :-1].values
train_classes = train_data.iloc[:, -1].values
test_features = test_data.iloc[:, :-1].values
test_classes = test_data.iloc[:, -1].values

In [13]:
train_data

AU01_r    AU02_r    AU04_r    AU05_r    AU06_r    AU07_r    AU09_r  \
0       0.00      0.00      1.83      2.59      0.00      0.92      0.00   
1       0.00      0.00      1.83      0.05      0.00      0.00      0.05   
2       0.00      0.22      1.52      1.20      0.57      0.00      0.71   
3       0.00      0.00      1.44      0.00      0.50      1.54      0.95   
4       0.96      0.10      2.46      0.56      0.00      1.07      0.00   
5       0.06      0.00      2.39      0.00      0.00      2.17      0.00   
6       0.34      0.33      0.11      0.50      0.00      0.00      0.00   
7       1.77      2.40      1.87      1.89      0.00      0.00      0.00   
8       0.00      0.00      2.82      0.11      0.00      0.27      0.34   
9       1.50      0.21      4.79      0.03      1.28      2.88      1.68   
10      1.37      0.00      2.26      1.67      0.79      1.93      1.09   
11      1.60      1.26      1.30      0.00      0.00      0.36      0.00   
12      0.08      0.00      3.66      0.93      0.65      2.13      0.67   
13      0.00      0.00      2.25      0.62      0.00      0.00      0.12   
14      0.00      0.00      1.92      0.00      0.10      1.38      0.70   
15      1.30      0.00      3.04      0.22      0.18      1.77      0.00   
16      0.00      0.00      0.93      0.00      1.55      4.16      3.78   
17      0.10      0.00      2.68      0.00      1.65      2.64      3.02   
18      0.76      0.00      0.00      0.29      2.62      1.03      0.24   
19      1.67      0.00      0.00      0.43      3.44      1.65      0.27   
20      0.00      0.00      0.00      0.57      2.71      1.42      0.68   
21      0.00      0.00      0.00      0.00      3.35      2.52      1.24   
22      0.42      0.00      2.22      0.00      3.20      1.47      1.32   
23      0.27      0.59      0.00      1.08      0.40      0.58      0.92   
24      1.10      1.32      0.58      0.10      3.92      2.38      2.13   
25      0.06      0.00      0.18      0.00      3.07      3.62      0.25   
26      0.00      0.00      0.00      0.38      2.17      1.84      0.00   
27      0.00      0.00      0.00      0.13      2.41      2.31      0.38   
28      0.93      0.00      0.00      0.00      2.12      0.97      0.00   
29      1.17      0.00      0.87      1.43      3.35      2.65      0.10   
30      0.33      0.00      0.11      0.00      1.88      2.28      1.14   
31      0.33      0.00      0.00      0.00      1.36      1.14      0.00   
32      0.00      0.00      0.00      0.70      1.93      0.59      0.00   
33      0.51      0.06      0.35      0.91      3.51      2.36      0.00   
34      0.00      0.00      0.00      0.00      0.83      1.14      0.01   
35      0.00      0.00      0.00      0.00      1.56      1.35      0.00   

      AU10_r    AU12_r    AU14_r    AU15_r    AU17_r    AU20_r    AU23_r  \
0       1.21      0.00      0.15      1.37      2.53      0.00      0.45   
1       0.84      0.00      1.30      2.05      2.07      2.07      0.94   
2       1.28      0.00      0.00      1.66      0.20      0.00      0.19   
3       1.07      0.00      0.00      1.07      1.14      0.64      0.00   
4       0.00      0.00      0.00      0.00      0.00      0.34      0.00   
5       0.00      0.00      0.00      1.85      0.48      0.88      0.16   
6       0.00      0.00      0.09      1.21      0.65      0.60      0.00   
7       0.05      0.00      0.02      0.68      0.00      0.00      0.00   
8       1.29      0.00      0.00      0.16      0.00      0.00      0.00   
9       2.04      0.08      0.00      0.00      0.00      0.00      0.00   
10      0.86      0.00      0.00      1.17      0.00      0.00      0.00   
11      0.91      0.52      0.00      0.78      0.41      0.43      0.00   
12      0.11      0.43      0.48      0.12      0.92      0.60      0.71   
13      0.08      0.43      0.00      1.22      0.84      0.21      0.03   
14      0.02      0.00      0.74      0.24      0.57 

In [6]:
test_classes

array(['frown', 'frown', 'frown', 'frown', 'frown', 'frown', 'frown',
       'frown', 'smile', 'smile', 'smile', 'smile', 'smile', 'smile',
       'smile', 'smile'], dtype=object)

In [7]:
test_features

array([[0.34, 0.44, 1.13, 0.18, 1.87, 3.55, 4.08, 1.35, 0.  , 0.54, 0.8 ,
        1.89, 0.  , 0.96, 0.74, 1.71, 0.57],
       [0.74, 0.  , 1.34, 0.  , 1.1 , 2.8 , 2.64, 1.35, 0.  , 0.2 , 0.8 ,
        0.  , 0.57, 0.34, 0.75, 0.27, 0.  ],
       [0.75, 0.07, 2.87, 0.02, 0.86, 1.34, 0.96, 1.68, 0.19, 1.14, 1.23,
        1.22, 0.  , 0.  , 0.84, 0.  , 0.  ],
       [0.15, 0.24, 2.79, 0.21, 0.79, 3.  , 0.36, 1.58, 0.  , 0.78, 1.14,
        1.36, 0.46, 0.17, 0.45, 0.99, 1.67],
       [1.05, 0.31, 3.95, 1.49, 2.27, 3.09, 2.3 , 3.43, 0.88, 1.27, 0.  ,
        0.  , 1.68, 0.  , 3.03, 1.04, 0.  ],
       [1.48, 0.83, 2.3 , 0.73, 0.61, 2.97, 0.76, 0.57, 0.  , 0.  , 0.17,
        0.66, 1.39, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 2.26, 0.53, 0.  , 0.85, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.07, 0.  , 1.87, 0.02, 0.38, 2.52, 0.  , 0.  , 0.54, 0.46, 0.  ,
        0.  , 0.46, 0.04, 0.53, 0.38, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.55, 2.61, 0.  

In [18]:
import numpy as np
import pandas as pd

# Step 1: Load the training and test data
train_data = pd.read_csv("training-part-2.csv")
test_data = pd.read_csv("test-part-2.csv")

# Step 2: Separate the feature vectors and classes
train_features = train_data.iloc[:, :-1].values
train_classes = train_data.iloc[:, -1].values
test_features = test_data.iloc[:, :-1].values
test_classes = test_data.iloc[:, -1].values

# Step 3: Calculate class priors
class_priors = {}
for class_label in np.unique(train_classes):
    class_priors[class_label] = np.mean(train_classes == class_label)

# Step 4: Calculate mean vectors and covariance matrices
class_means = {}
class_covs = {}
for class_label in np.unique(train_classes):
    class_features = train_features[train_classes == class_label]
    class_means[class_label] = np.mean(class_features, axis=0)
    class_covs[class_label] = np.cov(class_features, rowvar=False)

# Step 5: Implement Gaussian Discriminant Function
def gaussian_discriminant_function(x, class_label):
    mean = class_means[class_label]
    cov = class_covs[class_label]
    det = np.linalg.det(cov)
    inv = np.linalg.inv(cov)
    exponent = -0.5 * np.dot(np.dot((x - mean).T, inv), (x - mean))
    return 1 / (np.sqrt((2 * np.pi) ** len(mean) * det)) * np.exp(exponent)

# Step 6: Classify test data using Gaussian Discriminant Function
predicted_classes = []
for test_feature in test_features:
    probabilities = []
    for class_label in np.unique(train_classes):
        probability = gaussian_discriminant_function(test_feature, class_label) * class_priors[class_label]
        probabilities.append(probability)
    predicted_class = np.argmax(probabilities)
    predicted_classes.append(predicted_class)

# Step 7: Calculate error rate
error_rate = np.mean(predicted_classes != test_classes)

# Step 8: Calculate confusion matrix
# Print results
print("Error Rate:", error_rate)
print("Confusion Matrix:")
print(pd.crosstab(pd.Series(test_classes, name='Actual'), pd.Series(predicted_classes, name='Predicted')))


Error Rate: 1.0
Confusion Matrix:
Predicted  0  1
Actual         
frown      8  0
smile      4  4


In [17]:
conf_matrix 

array([[0., 0.],
       [0., 0.]])

In [10]:
# Step 3: Calculate class priors
class_priors = {}
for class_label in np.unique(train_classes):
    class_priors[class_label] = np.mean(train_classes == class_label)

# Step 4: Calculate mean vectors and covariance matrices
class_means = {}
class_covs = {}
for class_label in np.unique(train_classes):
    class_features = train_features[train_classes == class_label]
    class_means[class_label] = np.mean(class_features, axis=0)
    class_covs[class_label] = np.cov(class_features, rowvar=False)

# Step 5: Implement Gaussian Discriminant Function
def gaussian_discriminant_function(x, class_label):
    mean = class_means[class_label]
    cov = class_covs[class_label]
    det = np.linalg.det(cov)
    inv = np.linalg.inv(cov)
    exponent = -0.5 * np.dot(np.dot((x - mean).T, inv), (x - mean))
    return 1 / (np.sqrt((2 * np.pi) ** len(mean) * det)) * np.exp(exponent)

# Step 6: Classify test data using Gaussian Discriminant Function
predicted_classes = []
for test_feature in test_features:
    probabilities = []
    for class_label in np.unique(train_classes):
        probability = gaussian_discriminant_function(test_feature, class_label) * class_priors[class_label]
        probabilities.append(probability)
    predicted_class = np.argmax(probabilities)
    predicted_classes.append(predicted_class)

# Step 7: Calculate error rate
error_rate = np.mean(predicted_classes != test_classes)

In [11]:
error_rate

1.0

# TES

In [9]:
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, confusion_matrix

# Load data
train_data = pd.read_csv("training-part-2.csv")
test_data = pd.read_csv("test-part-2.csv")

# Extract features and labels
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]

# Initialize and fit the Gaussian Discriminant Analysis model
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

# Predict classes for the test set
y_pred = lda.predict(X_test)

# Evaluate the model
error_rate = 1 - accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print results
print("Error Rate:", error_rate)
print("Confusion Matrix:")
print(conf_matrix)


Error Rate: 0.0
Confusion Matrix:
[[8 0]
 [0 8]]


In [8]:
import pandas as pd

# Load data
train_data = pd.read_csv("training-part-2.csv")
test_data = pd.read_csv("test-part-2.csv")

# Calculate the sum of feature values for each class in the training set
sum_smile = train_data[train_data['Class'] == 'smile'].iloc[:, :-1].sum(axis=1).mean()
sum_frown = train_data[train_data['Class'] == 'frown'].iloc[:, :-1].sum(axis=1).mean()

# Classify instances in the test set based on the sum of feature values
predictions = []
for index, row in test_data.iterrows():
    sum_features = row.iloc[:-1].sum()
    predicted_class = 'smile' if abs(sum_features - sum_smile) < abs(sum_features - sum_frown) else 'frown'
    predictions.append(predicted_class)

# Evaluate the model
correct_predictions = (predictions == test_data['Class']).sum()
total_instances = len(test_data)
error_rate = (1 - (correct_predictions / total_instances))*100

# Print results
print("Error Rate:", error_rate)


Error Rate: 37.5


In [3]:
import pandas as pd
import numpy as np

# Load data
train_data = pd.read_csv("training-part-2.csv")
test_data = pd.read_csv("test-part-2.csv")

# Extract features and labels
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]

# Calculate Class Prior Probabilities
prior_smile = np.sum(y_train == 'smile') / len(y_train)
prior_frown = np.sum(y_train == 'frown') / len(y_train)

# Calculate Class Means
mean_smile = X_train[y_train == 'smile'].mean()
mean_frown = X_train[y_train == 'frown'].mean()

# Calculate Class Covariance Matrices
cov_smile = np.cov(X_train[y_train == 'smile'].T)
cov_frown = np.cov(X_train[y_train == 'frown'].T)

# Gaussian Discriminant Function
def gaussian_discriminant_function(x, mean, cov, prior):
    exponent = -0.5 * np.dot(np.dot((x - mean).T, np.linalg.inv(cov)), (x - mean))
    return exponent - 0.5 * np.log(np.linalg.det(cov)) + np.log(prior)

# Classify Test Set
predictions = []
for i in range(len(X_test)):
    x = X_test.iloc[i, :]
    g_smile = gaussian_discriminant_function(x, mean_smile, cov_smile, prior_smile)
    g_frown = gaussian_discriminant_function(x, mean_frown, cov_frown, prior_frown)

    predicted_class = 'smile' if g_smile > g_frown else 'frown'
    predictions.append(predicted_class)

# Evaluate
misclassifications = np.sum(predictions != y_test)
error_rate = (misclassifications / len(y_test))*100
print("Error Rate:", error_rate)


Error Rate: 6.25
